apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: istio-system
spec:
  project: default
  source:
    chart: istio/base
    repoURL: https://istio-release.storage.googleapis.com/charts
    helm:
      releaseName: istio-base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: istio-system
spec:
  project: default
  source:
    chart: istio/istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    helm:
      releaseName: istiod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  project: default
  source:
    chart: istio/gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    helm:
      releaseName: istio-ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
