apiVersion: v1
kind: Namespace
metadata:
  name: blog-app
---
apiVersion: v1
data:
  secret-access-credentials: SECRET_ACCESS_CREDS_PH
kind: Secret
metadata:
  creationTimestamp: "2023-09-04T07:23:32Z"
  name: gcpsm-secret
  namespace: blog-app
  resourceVersion: "20783"
  uid: b54cbf5a-c976-44a7-bc79-d61f20e42a50
type: Opaque
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: gcp-backend
  namespace: blog-app
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
        projectID: PROJECT_ID_PH
