name: Attest Images
on: [workflow_call]
jobs:
  binary-auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - id: gcloud-auth
      name: Authenticate with gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Set up Cloud SDK
      id: setup-gcloud-sdk
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Install gcloud beta
      id: install-gcloud-beta
      run: gcloud components install beta
    - name: Attest Images
      run: |
        grep -ir "image:" ./manifests | awk {'print $3'} > ./images
        echo "ghcr.io/external-secrets/external-secrets:v0.9.4" >> ./images
        for image in $(grep -ir "image:" ./manifests | awk {'print $3'}); do
          no_of_slash=$(echo $image | tr -cd '/' | wc -c)
          if [ $no_of_slash -eq 1 ]; then
            image="docker.io/$image"
          fi
          if [ $no_of_slash -eq 0 ]; then
            image="docker.io/library/$image"
          fi
          DIGEST=$(docker pull $image | grep Digest | awk {'print $2'})
          image_name=$(echo $image | awk -F ':' {'print $1'})
          attestation_present=$(gcloud beta container binauthz attestations list --attestor-project="${{ secrets.PROJECT_ID }}" --attestor="${{ secrets.ATTESTOR_NAME }}" --artifact-url="${image_name}@${DIGEST}")
          if [ -z "${attestation_present// }" ]; then
            gcloud beta container binauthz attestations sign-and-create --artifact-url="${image_name}@${DIGEST}" --attestor="${{ secrets.ATTESTOR_NAME }}" --attestor-project="${{ secrets.PROJECT_ID }}" --keyversion-project="${{ secrets.PROJECT_ID }}" --keyversion-location="${{ secrets.KMS_KEY_LOCATION }}" --keyversion-keyring="${{ secrets.KMS_KEYRING_NAME }}" --keyversion-key="${{ secrets.KMS_KEY_NAME }}" --keyversion="${{ secrets.KMS_KEY_VERSION }}"
          fi
        done
